### ISSUE TITLE
octicon "scroll to" anchors get hidden under the header

### ISSUE THREAD

**Issue by bennypowers** [daKmoR/rocket#136]
When adding headings to a page in markdown, "anchor" links are automatically added, e.g. `/guides/docs/#building`. Clicking on one of those links will scroll the page to that anchor, but it will be hidden behind the header.

One solution could be to add padding to the top of the content area equal to the height of the header.

**Comment by daKmoR** [comment]
that should not be the case see for example
https://wip-rocket.netlify.app/docs/launch-theme/inline-notification/#modify-the-title

it works by setting
```css
main > * {
  scroll-margin-top: 85px;
}
```

did you maybe have overwritten it?

**Comment by bennypowers** [comment]
Must be. Recent changes to my site have restored expected behaviour.

Thanks for the :eyes:. closing as solved
