### ISSUE TITLE
Support .jpeg assets

### ISSUE THREAD

**Issue by gdbaldw** [daKmoR/rocket#138]
Build fails to copy .jpeg assets.

To recreate failure, rename a .jpg asset to .jpeg, then build.

**Comment by daKmoR** [comment]
where is the image located? and which code users it how?

**Comment by gdbaldw** [comment]
Where?
In a sub-sub-folder under /docs

/docs/A/B/images/C.jpg copies into _site_dev/A/B/images/C.jpg

But, /docs/A/B/images/C.jpeg does not copy.

Which code?
$ yarn start
Copy occurs for jpg, does not for jpeg

$ yarn build
Fails with Error when rollup cannot find the .jpeg file in _site_dev

**Comment by daKmoR** [comment]
I meant more like how is it used in the html 😅

in most cases, Rocket does not need any copying of images/assets as it auto-detects assets within html and js.

e.g.
```html
<img src="../foo.jpeg" alt="foo" />
```
or
```js
const imgUrl = new URL('../bar.jpeg', import.meta.url).href;

const img = document.createElement('img');
img.src = imgUrl;
```

will not require any copying 💪

Therefore I'm wondering how you use it which would require copying 🤔

**Comment by gdbaldw** [comment]
Oh! My two test cases are front matter in YAML format, and as a Markdown link:

1. In front matter (e.g. the rocket "blog" theme)

> '---'
> cover_image: /A/B/images/C.jpg
> '---'

2. As a markdown link
`
[image](/A/B/images/C.jpg)
`

**Comment by daKmoR** [comment]
I thought about this the wrong way... I thought the problem was with rollup but it's probably with 11ty...

can you try adding `.jpeg` to this copy command
https://github.com/daKmoR/rocket/blob/master/packages/cli/src/shared/.eleventy.cjs#L48

**Comment by gdbaldw** [comment]
Yes, that's it!

> can you try adding .jpeg to this copy command
https://github.com/daKmoR/rocket/blob/master/packages/cli/src/shared/.eleventy.cjs#L48
