### ISSUE TITLE
Auto generate social media images

### ISSUE THREAD

**Issue by daKmoR** [daKmoR/rocket#148]
There are multiple options

here is one starting point
- https://www.juanfernandes.uk/blog/automated-open-graph-images-with-11ty-and-cloudinary/
- https://github.com/jlengstorf/get-share-image#readme

questions:
- use a service?
- or local image generation?
- we will need image optimization anyways so tool should be available
- how to cache, ...

**Comment by bennypowers** [comment]
maybe recommend to cache at edge servers, or use a function to download a copy once generated to assets

**Comment by daKmoR** [comment]
another nice approach using wasm
https://codepunkt.de/writing/generating-beautiful-open-graph-images-with-nodejs/

**Comment by daKmoR** [comment]
official eleventy image plugin can be used as well

https://github.com/11ty/eleventy-img/issues/40

**Comment by bennypowers** [comment]
yeah that's good stuff, I'm leaning towards the official plugin, but does it do the kind of layering and text manipulation we need?

**Comment by daKmoR** [comment]
I think so... seems to support full svg rendering 👍

**Comment by daKmoR** [comment]
has been implemented via `@11ty/eleventy-img` 💪
