### ISSUE TITLE
internal links and _site-dev

### ISSUE THREAD

**Issue by bennypowers** [daKmoR/rocket#149]
Authors will want to link to pages from the web root, i.e.

```markdown
[script children](/guides/cool-tricks/inline-query-scripts)
```

instead of 
```markdown
[script children](../../../guides/cool-tricks/inline-query-scripts)
```

But during dev-time the site is served from `_site-dev`.

Either that prefix should not be used (perhaps the export map update to web dev server can help with that), or internal links should be automatically rewritten at dev-time.

**Comment by daKmoR** [comment]
we now serve without a subdirectory 👍

so such links should work 💪
