### ISSUE TITLE
Don't handle redirects in the Service Worker

### ISSUE THREAD

**Issue by bennypowers** [daKmoR/rocket#152]
As per @thepassle, we should not handle redirects in the sw for an MPA, rather in the server, e.g. netlify.

see also https://blog.kiprosh.com/show-custom-404-error-page-for-netlify-applications/

**Comment by bennypowers** [comment]
See https://github.com/GoogleChrome/workbox/issues/2682#issuecomment-735992722

**Comment by daKmoR** [comment]
we no longer set a `navigateFallback` so servers are free to handle this now 👍
