### ISSUE TITLE
_site breaks, whereas _site-dev works correctly for internal href

### ISSUE THREAD

**Issue by gdbaldw** [daKmoR/rocket#160]
With this template...
```
      <a href="{{ display_image | url }}">
        <img src="{{ catalog_image | url }}" alt="">
      </a>
```
...and markdown front matter referencing two internal jpg assets colocated in one subdirectory,
_site has the correctly transformed `src` attribute, but the `href` attribute is passed through unchanged and its referenced jpg is not copied over.

As a result: _site-dev works as intended at this anchor tag, but _site yields a 404 Error.

**Comment by daKmoR** [comment]
with the latest release, we now serve `_site-dev` no longer as a subdirectory but as the root-dir... e.g. the URLs for dev and build output should be exactly the same.

I think this should solve your issue as well. If not feel free to reopen or creating another issue 🤗
