### ISSUE TITLE
Split launch into smaller packages

### ISSUE THREAD

**Issue by jorgecasar** [daKmoR/rocket#94]
Currently, launch package has a lot of things also that we have to find a way to make it more scalable and interchangeable.

I'm opening this issue to discuss about naming convention and best practices to be easy to include in your project or rewrite with the less pain possible.

We can start with a list of sections, we can use [Nunjucks Blocks](https://mozilla.github.io/nunjucks/templating.html#template-inheritance) to define them. This package should have Nunjucks files, minimal css to make it work, and collections definitions.

1. Site
2. Blog
3. E-commerce

To work with layouts we need to define the layout parts, that could be included or not in the project and layout should be compatible with that:

1. Header
2. Sidebar
3. Main
4. Footer

And finally we can have several design for each site, then could be different set of assets.

**Comment by daKmoR** [comment]
Nunjucks Blocks looks really nice 👍

yeah there definitely needs to be some best practices for how to structure "themes"...

especially as multiple themes should be able to be combined... and ultimately every site has a "user theme" which is the local docs so you can adjust/override every file...
